### ISSUE TITLE
on display multiple operators gets visible, but last operator get selected for execution as expected

### ISSUE THREAD

**Issue by BanksBond** [BanksBond/caculator-task4#1]
![image](https://github.com/BanksBond/caculator-task4/assets/104974164/61d1c43e-5114-465d-bfe3-1389dcbd8151)

**Comment by Swapnil-Ghodse** [comment]
Hey @BanksBond , Hope you are doing well. Can I get to work on this issue?

**Comment by BanksBond** [comment]
> Hey @BanksBond , Hope you are doing well. Can I get to work on this issue?

Hello @Swapnil-Ghodse I am doing great and yes you can  work on this issue and also do me a favour to tell me how you resolve this as I am just a newbie in React. 😅

**Comment by Swapnil-Ghodse** [comment]
Thanks  and sure I will attach the solution also.

**Comment by Swapnil-Ghodse** [comment]
Hi @BanksBond , I have made the required changes, please let me know if you are able to see the PR and if 'yes' please review it and merge.

Explaination:

Created new function **compareSignExpresion**  to handle the issue.

` const lastelement = expression?.slice(-1)
    
    let reg = new RegExp('^[0-9]$');
    const result =  (lastelement === '+' || lastelement === '-' || lastelement === 'X' || lastelement === '/') ? (expression.slice(0, -1 ) + sign) : expression + sign
    return result;
`

**Comment by BanksBond** [comment]
> Hi @BanksBond , I have made the required changes, please let me know if you are able to see the PR and if 'yes' please review it and merge.
> 
> Explaination:
> 
> Created new function **compareSignExpresion** to handle the issue.
> 
> ` const lastelement = expression?.slice(-1)
> 
> ```
> let reg = new RegExp('^[0-9]$');
> const result =  (lastelement === '+' || lastelement === '-' || lastelement === 'X' || lastelement === '/') ? (expression.slice(0, -1 ) + sign) : expression + sign
> return result;
> ```
> 
> `

Hi @Swapnil-Ghodse your PR is not visible here.

**Comment by BanksBond** [comment]
Merged your pull request, thank you so much @Swapnil-Ghodse for helping ❤
